version: '3.9'

networks:
    api-network:
        driver: bridge

services:
    identity.api:
        image: ${DOCKER_REGISTRY-}twisioidentityapi
        container_name: identity.api
        build:
            context: .
            dockerfile: TWISIO.Identity/Dockerfile
        ports:
            - "80:80"
        networks:
            - api-network
        depends_on:
            - postgres_db        
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        environment:
            JWT:SecretKey: $JWT:SecretKey
            JWT:Issuer: $JWT:Issuer
            JWT:Audience: $JWT:Audience
            ConnectionStrings:PostgreSQL: $ConnectionString
            SMTP:Name: $SMTP:Name
            SMTP:Username: $SMTP:Username
            SMTP:Password: $SMTP:Password
            SMTP:Port: $SMTP:Port
            SMTP:Host: $SMTP:Host
    
    postgres_db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        ports:
            - "5432:5432"
        networks:
            - api-network
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: